apiVersion: v1
kind: Pod
metadata:
  name: irods-pod
  namespace: thimo
spec:
  containers:
    - image: coffeeginger/irods_catalog:latest
      name: irods-catalog
      env:
        - name: POSTGRES_PASSWORD
          value: "testpassword"
      ports:
        - containerPort: 5432
          name: ic-port
    - image: coffeeginger/irods_catalog_provider:latest
      name: irods-catalog-provider
      ports:
        - containerPort: 1247
          name: icp-port
  imagePullSecrets:
    - name: thimo-secret

