apiVersion: v1
kind: Secret
metadata:
  name: thimo-secret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlkyOW1abVZsWjJsdVoyVnlPbVJqYTNKZmNHRjBYMmhqUTJ0S2RIWnVhRTlzV0dGd2NtWXhYekJzV0VWQ00ybENhdz09IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
